### ISSUE TITLE
Variáveis em espanhol

### ISSUE THREAD

**Issue by ErickVal** [cyz/xamarin-ambiente-teste#1]
Seria maratona Xamarin Brasil, mas todas variáveis se encontram em espanhol, dificultando o entendimento.

----UPDATE----
Repositório Original:
https://github.com/aminespinoza/EnviaCorreosXamarinApp

**Comment by cyz** [comment]
@ErickVal nessa primeira fase da maratona temos que utilizar esse material e app :/
