### ISSUE TITLE
Error while trying to execute the solutions

### ISSUE THREAD

**Issue by JGeraldoLima** [cyz/xamarin-ambiente-teste#2]
Hi, I'm trying to execute this project solutions, following the README instructions, but the following errors keep occuring:
![image](https://cloud.githubusercontent.com/assets/6726996/22186243/c9a1fe5c-e0d9-11e6-8aeb-d540ce8f0784.png)

I searched for this XamlCTask but I didn't find it. Can anyone help me?

**Comment by crawletas** [comment]
same problem here

**Comment by devmvrborges** [comment]
i too :(

**Comment by manduruca** [comment]
Me too...
![error](https://cloud.githubusercontent.com/assets/25320708/22244344/4ce8a282-e212-11e6-993e-5e6120de4d92.png)

**Comment by diegofachin** [comment]
Same problem here too

**Comment by sfmendon** [comment]
I have the same mistakes,  @JGeraldoLima .

**Comment by jaiconM** [comment]
O mesmo problema aqui. 
Same problem here.

Error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error		The "XamlCTask" task could not be instantiated from "D:\Curso Maratona Xamarin\xamarin-ambiente-teste-master\EjercicioBase\packages\Xamarin.Forms.2.0.0.6482\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\Xamarin.Forms.Build.Tasks.dll". Could not load file or assembly 'Xamarin.Forms.Build.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)	EnviarCorreo.Forms			
`

**Comment by jaiconM** [comment]
Pessoal, resolvi esse problema atualizando a referencia do Xamarin.Forms via Manage Nuget Packages.
Tem que atualizar nesses dois projetos: EnviarCorreo.Forms e EnviarCorreo.Forms.Droid

Solved this issue updating the reference of Xamarin.Forms with Manage Nuget Packages.
Need to update this 2 projects: EnviarCorreo.Forms e EnviarCorreo.Forms.Droid

**Comment by sfmendon** [comment]
Great, @jaiconM .  I will test later.

**Comment by jabiraka** [comment]
@jaiconM , amigo, como que faz essa parada de atualizar referência? Faz isso em Ferramentas -> Gerenciador de Pacotes do Nuget -> Gerenciar Pacotes do Nuget para a Solução ?

**Comment by JrGirotto** [comment]
Companheiro ainda estou instalando o Visual. Mas vamos nos falando.

www.polishop.vc/jrgirotto


________________________________

**Comment by jabiraka** [comment]
Realmente, fazendo o procedimento de atualizar o xamarin.forms o programa roda, mas qdo abre no emulador as aplicações, ele abre e fecha rápido, acho que não  executou. Alguém mais com esse problema?

**Comment by denstorti** [comment]
@jabiraka 
Worked for me, try this:

1. Close solution 
2. Delete the 'package' folder in your solution directory 
3. Open solution and built it to install nuget packages again.
