### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by JosafaOrrico** [cyz/xamarin-ambiente-teste#4]
I can not solve the problem of nuget packages. Already installs almost all, I have installed Bcl.Build and others. My Mac OS El Captain and VS for Mac Preview 3.
I always get the message:

Warning: All projects referencing EnviarCorreo.Forms.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569. (EnviarCorreo.Nativo)

**Comment by cyz** [comment]
All packages was removed from project. Please, check the update and try run again. Alternative, you can use Xamarin Studio in your Mac OS.
