### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by pbalbino** [cyz/xamarin-ambiente-teste#7]
Ao compilar a solução foi apresentado um erro na linha:
`PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));`

Removi o caracter "?" deixando a linha da seguinte forma:
`PropertyChanged.Invoke(this, new PropertyChangedEventArgs(propertyName));`

Com isso consegui compilar a solução e comecei o teste pelo projeto "EnviarCorreo.Nativo". O teste funcionou corretamente, fiz o deploy em um tablet, tudo certo.

Porém ao testar o projeto "EnviarCorreo.Forms.Droid" ocorre o seguinte erro: "System.NullReferenceException: Object reference not set to an instance of an object." na mesma linha mencionada acima.

Alguém com o mesmo erro?

**Comment by pbalbino** [comment]
Corrigi o problema da seguinte forma:
`if (PropertyChanged != null)`
`{`
`PropertyChanged.Invoke(this, new PropertyChangedEventArgs(propertyName));`
`}`

**Comment by felipemfp** [comment]
O operador `?` chegou na versão 6.0 do C#. É um atalho para verificar se é `null` antes de realizar a "operação".

[Mais detalhes](https://msdn.microsoft.com/pt-br/magazine/Dn879355.aspx)

**Comment by pbalbino** [comment]
Obrigado pela informação @felipemfp , eu estou usando o visual studio 2013, li no link que você disponibilizou que o compilador capaz de reconhecer esse operador foi disponibilizado na versão 2015, creio que foi por isso o erro foi apresentado...obrigado!
