### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by alextochetto** [cyz/xamarin-ambiente-teste#9]
How I fix this error: Severity	Code	Description	Project	File	Line	Suppression State
Error		java.lang.UnsupportedClassVersionError: com/android/dx/command/Main  :  Unsupported major.minor version 52.0	EnviarCorreo.Forms.Droid			
I'm trying to run Forms.Droid!!

**Comment by karlosmorais** [comment]
Hi, I had the same problem. And the solution is to install the Java SDK version 1.8 and change the VS options

**Comment by joseBarreto** [comment]
My set up for version 1.7. Will that keep me from following the lessons?

I can not run the project in this version. I get several errors.

**Comment by alextochetto** [comment]
1 - I installed the JDK 8_121 x86
2 - Change de VS 2015 configuration on Tools >  Options > Xamarin > Change de Kit location to the new JDK
3 - Reboot the PC
4 - Opne and clean de solution
5 - Rebuild
6 - It´s working!!! LOL
